#!/bin/sh

### BEGIN INIT INFO
# Provides:          vlc
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: vlc
# Description:       transport rtp from localhost to http
### END INIT INFO

VLC_USER=pi
VLC_PORT=8080

start()
{
	echo "Starting vlc ..."
	sudo -u $VLC_USER cvlc v4l2:///dev/video0:chroma=h264:width=800:height=600 :input-slave="alsa://hw:1,0" --sout '#transcode{aenc=ffmpeg{strict=-2},acodec=mp4a,ab=32}:http{mux=ts,dst=:$VLC_PORT}' -vvv > /dev/null 2>&1  &
}

stop()
{
	echo "Stopping vlc ..."
	kill -9 $(pidof vlc) >/dev/null 2>&1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		;;
esac

exit 0
